import React from "react";
import { FileText } from "lucide-react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4">
      <div className="bg-white rounded-xl shadow-lg max-w-2xl w-full p-8">
        <div className="flex items-center gap-3 mb-6">
          <FileText className="text-[#8C52FF]" size={32} />
          <h1 className="text-3xl font-bold">Terms and Conditions</h1>
        </div>
        <div className="prose prose-lg">
          <p>Last updated: {new Date().toLocaleDateString()}</p>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By using InterviewIQ (the "Service"), you agree to these Terms and Conditions. If you do not agree, please do not use the Service.
          </p>
          <h2>2. Accounts</h2>
          <p>
            You may need to create an account to use certain features. You are responsible for maintaining the security of your account and for all activities that occur under your account.
          </p>
          <h2>3. Use of the Service</h2>
          <p>
            You agree to use InterviewIQ for lawful purposes only. You may not use the Service to abuse free trials, attempt to circumvent usage limits, or engage in any activity that could harm the Service or its users.
          </p>
          <h2>4. Paid Subscriptions</h2>
          <p>
            InterviewIQ offers paid subscription plans that provide additional features and increased usage limits. By subscribing, you agree to pay the applicable fees. Subscription fees are billed in advance and are non-refundable. You may cancel your subscription at any time, but no refunds will be provided for unused portions of your subscription period.
          </p>
          <h2>5. Data and Privacy</h2>
          <p>
            Please review our <a href="/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a> to understand how we collect, use, and protect your information.
          </p>
          <h2>6. Third-Party Services</h2>
          <p>
            InterviewIQ uses third-party services such as OpenAI (for generating reports) and Supabase (for authentication and data storage). By using the Service, you consent to your data being processed by these providers as described in our Privacy Policy.
          </p>
          <h2>7. Disclaimer</h2>
          <p>
            The Service is provided "as is" without warranties of any kind. We do not guarantee the accuracy, completeness, or usefulness of any information generated by the Service. Use the Service at your own risk.
          </p>
          <h2>8. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, InterviewIQ and its owners shall not be liable for any damages arising from your use of the Service.
          </p>
          <h2>9. Changes to Terms</h2>
          <p>
            We may update these Terms and Conditions from time to time. We will notify users of significant changes by updating the date at the top of this page. Continued use of the Service after changes constitutes acceptance of the new terms.
          </p>
          <h2>10. Contact</h2>
          <p>
            If you have any questions about these Terms, please contact us at contactinterviewiq@gmail.com.
          </p>
        </div>
        <div className="mt-8 text-center">
          <Link href="/" className="text-blue-600 hover:underline font-semibold">
            ← Back to Home
          </Link>
        </div>
      </div>
    </main>
  );
} 